### GET - List of Reviews
GET {{host}}/reviews

### POST - Create a Review
POST {{host}}/reviews
Content-Type: application/json

{
  "full_name": "ADAM GP",
  "position": "Fullstack Dev",
  "relation": "colleague",
  "company": "Company",
  "review": "This product exceeded my expectations. The quality is top-notch and the customer service was excellent."
}